set_property SRC_FILE_INFO {cfile:C:/Users/coal/Documents/coalarchive/USU/FALL24/ece2700/fsmfinal/fsmfinal.srcs/constrs_1/imports/ece2700/Basys3_Master.xdc rfile:../../../fsmfinal.srcs/constrs_1/imports/ece2700/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {rstn}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {w}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {z}]
